### ISSUE TITLE
Add to Sidebar option

### ISSUE THREAD

**Issue by ifeign** [davide125/hassio-addons#8]
Would you be able to add the "add to sidebar" toggle that many addons have so that it doesn't have to be done manually in the config file?

**Comment by davide125** [comment]
Last time I tried it didn't load properly from the sidebar due to some CORS issue, but that might be fixable. Does it work for you if you add it in the config?

**Comment by ifeign** [comment]
I just put this in my config, but I'm sure there's a better way to do it so I can access that panel remotely:
```
panel_iframe:
  homebridge:
    title: Homebridge
    icon: mdi:home-automation
    url: http://homeassistant.local:8581
```
